[[proxy]]
rewrite = "/api"
backend = "http://127.0.0.1:3000"

[build]
target = "index.html"
dist = "dist"
watch = ["src/**/*.rs", "index.html", "style/input.css"] 

# Hook pour exécuter Tailwind CSS
[[hooks]]
stage = "build"
command = "sh"
command_arguments = [
  "-c",
  "npx tailwindcss -i style/input.css -o style/output.css"
]
